/**
 * NOTE: This class is auto generated by the swagger code generator program (2.3.1).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.sukrut.fsd.api;

import com.sukrut.fsd.model.Offers;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2019-06-14T04:59:45.171+05:30")

@Api(value = "storeOffers", description = "the storeOffers API")
public interface StoreOffersApi {

    @ApiOperation(value = "Add offers by vendor", nickname = "getofferByproductName", notes = "vendor will able to add offers", response = Offers.class, responseContainer = "List", tags={ "offers", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successful operation", response = Offers.class, responseContainer = "List"),
        @ApiResponse(code = 400, message = "Invalid Name supplied"),
        @ApiResponse(code = 404, message = "Store not found  ") })
    @RequestMapping(value = "/storeOffers/add",
        produces = { "application/json" }, 
        method = RequestMethod.POST)
    ResponseEntity<List<Offers>> getofferByproductName(@ApiParam(value = "offers should be displayed" ,required=true )  @Valid @RequestBody Offers body);

}
