/**
 * NOTE: This class is auto generated by the swagger code generator program (2.3.1).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.sukrut.fsd.api;

import com.sukrut.fsd.model.VendorOnboard;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2019-06-14T04:59:45.171+05:30")

@Api(value = "vendorOnboard", description = "the vendorOnboard API")
public interface VendorOnboardApi {

    @ApiOperation(value = "Accept the vendorOnboard terms", nickname = "acceptTerms", notes = "Accept the vendorOnboard terms", tags={ "vendorOnboard", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successful operation"),
        @ApiResponse(code = 405, message = "Invalid input") })
    @RequestMapping(value = "/vendorOnboard/accept",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<Void> acceptTerms();


    @ApiOperation(value = "Get all vendorOnboarded list", nickname = "getvendorOnboardList", notes = "Returns the list of all vendorOnboarding to the Sukrut application", response = VendorOnboard.class, responseContainer = "List", tags={ "vendorOnboard", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successful operation", response = VendorOnboard.class, responseContainer = "List") })
    @RequestMapping(value = "/vendorOnboard/all",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<List<VendorOnboard>> getvendorOnboardList();


    @ApiOperation(value = "Upload Vendor Onboard information", nickname = "uploadInformation", notes = "Upload Vendor Onboard information", response = VendorOnboard.class, responseContainer = "List", tags={ "vendorOnboard", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "successful operation", response = VendorOnboard.class, responseContainer = "List"),
        @ApiResponse(code = 400, message = "invalid input") })
    @RequestMapping(value = "/vendorOnboard/upload",
        produces = { "application/json" }, 
        method = RequestMethod.POST)
    ResponseEntity<List<VendorOnboard>> uploadInformation(@ApiParam(value = "Vendor provides all the details" ,required=true )  @Valid @RequestBody VendorOnboard body);

}
